apiVersion: v2
appVersion: 2.1.3
dependencies:
- condition: opentelemetry-collector.enabled
  name: opentelemetry-collector
  repository: https://open-telemetry.github.io/opentelemetry-helm-charts
  version: 0.134.0
- condition: jaeger.enabled
  name: jaeger
  repository: https://jaegertracing.github.io/helm-charts
  version: 3.4.1
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 27.39.0
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 10.1.2
- condition: opensearch.enabled
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 3.2.1
description: opentelemetry demo helm chart
home: https://opentelemetry.io/
icon: https://opentelemetry.io/img/logos/opentelemetry-logo-nav.png
maintainers:
- name: dmitryax
- name: jaronoff97
- name: julianocosta89
- name: puckpuck
- name: tylerhelmuth
name: opentelemetry-demo
sources:
- https://github.com/open-telemetry/opentelemetry-demo
type: application
version: 0.38.6
