// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/credentials/add": {
            "post": {
                "description": "Submits a credential (VC or manual document ref) for asynchronous verification, creating a credential token in 'Pending' state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "Add a credential for verification",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.Request-validation_AddCredentialRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Credential accepted for verification",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_AddCredentialSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_BadRequestExample"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. JWT missing, invalid, or expired.",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_UnauthorizedExample"
                        }
                    },
                    "404": {
                        "description": "Document ID not found",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_DocumentNotFoundExample"
                        }
                    }
                }
            }
        },
        "/credentials/delete": {
            "post": {
                "description": "Delete credential for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "Delete credential",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.Request-validation_DeleteCredentialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_DeleteCredentialResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_BadRequestExample"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. JWT missing, invalid, or expired.",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_UnauthorizedExample"
                        }
                    },
                    "404": {
                        "description": "Credential not found",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_NotFoundExample"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_ParamsInternalExample"
                        }
                    }
                }
            }
        },
        "/credentials/get": {
            "post": {
                "description": "Get credential for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "Get credential",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.Request-validation_GetCredentialRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_CredentialsSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_BadRequestExample"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. JWT missing, invalid, or expired.",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_UnauthorizedExample"
                        }
                    },
                    "404": {
                        "description": "Credential not found",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_NotFoundExample"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_ParamsInternalExample"
                        }
                    }
                }
            }
        },
        "/credentials/list": {
            "post": {
                "description": "List all credentials for a user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "List credentials",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/response.Request-validation_ListCredentialsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_ListCredentialsSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_BadRequestExample"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. JWT missing, invalid, or expired.",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_UnauthorizedExample"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_ParamsInternalExample"
                        }
                    }
                }
            }
        },
        "/credentials/upload": {
            "post": {
                "description": "Uploads a document (e.g., passport) for manual verification. Returns a document ID used in /credentials/add.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Credentials"
                ],
                "summary": "Upload a document for verification",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Document to upload",
                        "name": "document",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Document uploaded successfully",
                        "schema": {
                            "$ref": "#/definitions/response.Response-response_UploadCredentialResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_BadRequestExample"
                        }
                    },
                    "401": {
                        "description": "Unauthorized. JWT missing, invalid, or expired.",
                        "schema": {
                            "$ref": "#/definitions/example.ErrorEnvelope-example_UnauthorizedExample"
                        }
                    }
                }
            }
        },
        "/health-check": {
            "get": {
                "description": "Check the status of services and database connections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/example.HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/example.HealthCheckResponseError"
                        }
                    }
                }
            }
        },
        "/v1/actor/create": {
            "post": {
                "description": "Creates a new user actor, generates and stores the reproducible DID from the master public key, and links them.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Register a new actor",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_RegistrationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_RegistrationSuccess"
                        }
                    },
                    "400": {
                        "description": "Bad request, such as a missing required field",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    },
                    "409": {
                        "description": "Conflict, an identifier is already in use",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        },
        "/v1/actor/forgotPassword": {
            "post": {
                "description": "Initiates the password reset flow for a given email address. A reset link will be sent to the user's email.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Forgot password",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_ForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Success"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        },
        "/v1/actor/getProfile": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the full actor profile for the authenticated actor.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Get current actor's profile",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_Empty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_ActorProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        },
        "/v1/actor/login": {
            "post": {
                "description": "Authenticates an actor and returns JWT tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Login actor",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        },
        "/v1/actor/resolve": {
            "post": {
                "description": "Publicly resolves a universal identifier to its master public key and DID.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Resolve a universal identifier",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_ResolveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_ResolveResponse"
                        }
                    },
                    "404": {
                        "description": "Not found",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        },
        "/v1/actor/signout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logs out the user from auth provider and revokes all their active sessions.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Actor signout",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_Empty"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Success"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        },
        "/v1/actor/update": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Allows an authenticated user to update their profile information, such as name and phone number. The actor to update is determined by the session token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Actor"
                ],
                "summary": "Update actor profile",
                "parameters": [
                    {
                        "description": "Request body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/validation.ApiRequest_UpdateActorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_ActorProfile"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    },
                    "409": {
                        "description": "Conflict, the new phone number is already in use",
                        "schema": {
                            "$ref": "#/definitions/response.ApiResponse_Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "example.BadRequestExample": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string",
                    "example": "BAD_REQUEST"
                },
                "errmsg": {
                    "type": "string",
                    "example": "Invalid request body"
                },
                "msgid": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                },
                "status": {
                    "type": "string",
                    "example": "failed"
                }
            }
        },
        "example.DocumentNotFoundExample": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string",
                    "example": "DOCUMENT_NOT_FOUND"
                },
                "errmsg": {
                    "type": "string",
                    "example": "Document ID not found"
                },
                "msgid": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                },
                "status": {
                    "type": "string",
                    "example": "failed"
                }
            }
        },
        "example.ErrorEnvelope-example_BadRequestExample": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/example.BadRequestExample"
                },
                "response": {
                    "type": "object"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "example.ErrorEnvelope-example_DocumentNotFoundExample": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/example.DocumentNotFoundExample"
                },
                "response": {
                    "type": "object"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "example.ErrorEnvelope-example_NotFoundExample": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/example.NotFoundExample"
                },
                "response": {
                    "type": "object"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "example.ErrorEnvelope-example_ParamsInternalExample": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/example.ParamsInternalExample"
                },
                "response": {
                    "type": "object"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "example.ErrorEnvelope-example_UnauthorizedExample": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/example.UnauthorizedExample"
                },
                "response": {
                    "type": "object"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "example.HealthCheck": {
            "type": "object",
            "properties": {
                "is_up": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Postgre"
                },
                "status": {
                    "type": "string",
                    "example": "Up"
                }
            }
        },
        "example.HealthCheckError": {
            "type": "object",
            "properties": {
                "is_up": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "failed to connect to 'host=localhost user=postgres database=wrongdb': server error (FATAL: database \"wrongdb\" does not exist (SQLSTATE 3D000))"
                },
                "name": {
                    "type": "string",
                    "example": "Postgre"
                },
                "status": {
                    "type": "string",
                    "example": "Down"
                }
            }
        },
        "example.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "is_healthy": {
                    "type": "boolean",
                    "example": true
                },
                "message": {
                    "type": "string",
                    "example": "Health check completed"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example.HealthCheck"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "example.HealthCheckResponseError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 500
                },
                "is_healthy": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Health check completed"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/example.HealthCheckError"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "example.NotFoundExample": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string",
                    "example": "CREDENTIAL_NOT_FOUND"
                },
                "errmsg": {
                    "type": "string",
                    "example": "Credential not found"
                },
                "msgid": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                },
                "status": {
                    "type": "string",
                    "example": "failed"
                }
            }
        },
        "example.ParamsInternalExample": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string",
                    "example": "INTERNAL_SERVER_ERROR"
                },
                "errmsg": {
                    "type": "string",
                    "example": "Internal server error"
                },
                "msgid": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                },
                "status": {
                    "type": "string",
                    "example": "failed"
                }
            }
        },
        "example.UnauthorizedExample": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string",
                    "example": "UNAUTHORIZED"
                },
                "errmsg": {
                    "type": "string",
                    "example": "Unauthorized. The JWT is missing, invalid, or expired"
                },
                "msgid": {
                    "type": "string",
                    "example": "a1b2c3d4-e5f6-7890-1234-567890abcdef"
                },
                "status": {
                    "type": "string",
                    "example": "failed"
                }
            }
        },
        "response.ActorProfile": {
            "type": "object",
            "properties": {
                "countryOfIncorporation": {
                    "description": "Business fields",
                    "type": "string",
                    "example": "US"
                },
                "countryOfResidence": {
                    "type": "string",
                    "example": "US"
                },
                "did": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "email": {
                    "type": "string",
                    "example": "actor@example.com"
                },
                "entityType": {
                    "type": "string",
                    "example": "Individual"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "masterPublicKey": {
                    "type": "string",
                    "example": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n-----END PUBLIC KEY-----"
                },
                "nationality": {
                    "description": "Individual fields",
                    "type": "string",
                    "example": "US"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+1234567890"
                },
                "universalIdentifier": {
                    "type": "string",
                    "example": "actor123"
                },
                "verificationLevel": {
                    "type": "string",
                    "example": "Tier0_Unverified"
                }
            }
        },
        "response.AddCredentialSuccessResponse": {
            "type": "object",
            "properties": {
                "credentialId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "message": {
                    "type": "string",
                    "example": "Credential submitted successfully. Verification is in progress."
                },
                "status": {
                    "type": "string",
                    "example": "Pending"
                }
            }
        },
        "response.ApiResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/response.ApiResponseParams"
                },
                "response": {},
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.ApiResponseParams": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "errmsg": {
                    "type": "string"
                },
                "msgid": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "status": {
                    "type": "string",
                    "example": "successful"
                }
            }
        },
        "response.ApiResponse_ActorProfile": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/response.ApiResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.ActorProfile"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.ApiResponse_Error": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/response.ApiResponseParams"
                },
                "response": {},
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.ApiResponse_RegistrationSuccess": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/response.ApiResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.RegistrationSuccessResponse"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.ApiResponse_ResolveResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/response.ApiResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.ResolveResponse"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.ApiResponse_Success": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/response.ApiResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.SuccessResponse"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.CredentialsSuccessResponse": {
            "type": "object",
            "properties": {
                "credentialId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "status": {
                    "type": "string",
                    "example": "Pending"
                },
                "submittedAt": {
                    "type": "string",
                    "example": "2025-10-23T06:25:25.191Z"
                },
                "type": {
                    "type": "string",
                    "example": "VerifiableCredential"
                }
            }
        },
        "response.DeleteCredentialResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation successfully."
                }
            }
        },
        "response.ListCredentialsSuccessResponse": {
            "type": "object",
            "properties": {
                "credentials": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.CredentialsSuccessResponse"
                    }
                }
            }
        },
        "response.RegistrationSuccessResponse": {
            "type": "object",
            "properties": {
                "did": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "message": {
                    "type": "string",
                    "example": "Actor registered successfully"
                }
            }
        },
        "response.Request-validation_AddCredentialRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.AddCredentialRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Request-validation_DeleteCredentialRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.DeleteCredentialRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Request-validation_GetCredentialRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.GetCredentialRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Request-validation_ListCredentialsRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.ListCredentialsRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.RequestParams": {
            "type": "object",
            "properties": {
                "msgid": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "response.ResolveResponse": {
            "type": "object",
            "properties": {
                "did": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "masterPublicKey": {
                    "type": "string",
                    "example": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n-----END PUBLIC KEY-----"
                },
                "universalIdentifier": {
                    "type": "string",
                    "example": "user123"
                }
            }
        },
        "response.Response-response_AddCredentialSuccessResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.ResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.AddCredentialSuccessResponse"
                },
                "responseCode": {
                    "type": "string"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Response-response_CredentialsSuccessResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.ResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.CredentialsSuccessResponse"
                },
                "responseCode": {
                    "type": "string"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Response-response_DeleteCredentialResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.ResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.DeleteCredentialResponse"
                },
                "responseCode": {
                    "type": "string"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Response-response_ListCredentialsSuccessResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.ResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.ListCredentialsSuccessResponse"
                },
                "responseCode": {
                    "type": "string"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.Response-response_UploadCredentialResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api_id"
                },
                "params": {
                    "$ref": "#/definitions/response.ResponseParams"
                },
                "response": {
                    "$ref": "#/definitions/response.UploadCredentialResponse"
                },
                "responseCode": {
                    "type": "string"
                },
                "ts": {
                    "type": "string",
                    "example": "2025-09-08T12:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "v1"
                }
            }
        },
        "response.ResponseParams": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "string"
                },
                "errmsg": {
                    "type": "string"
                },
                "msgid": {
                    "type": "string"
                },
                "resmsgid": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "response.SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Operation completed successfully"
                }
            }
        },
        "response.UploadCredentialResponse": {
            "type": "object",
            "properties": {
                "documentId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "status": {
                    "type": "string",
                    "example": "Uploaded. Awaiting verification."
                }
            }
        },
        "validation.AddCredentialRequest": {
            "type": "object",
            "properties": {
                "payload": {
                    "$ref": "#/definitions/validation.CredentialPayload"
                },
                "verificationType": {
                    "type": "string",
                    "example": "VC"
                }
            }
        },
        "validation.ApiRequest_Empty": {
            "type": "object",
            "required": [
                "id",
                "ts",
                "ver"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/validation.RequestParams"
                },
                "request": {
                    "type": "object"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "5.0.0"
                }
            }
        },
        "validation.ApiRequest_ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "id",
                "ts",
                "ver"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/validation.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.ForgotPasswordRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "5.0.0"
                }
            }
        },
        "validation.ApiRequest_LoginRequest": {
            "type": "object",
            "required": [
                "id",
                "ts",
                "ver"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/validation.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.LoginRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "5.0.0"
                }
            }
        },
        "validation.ApiRequest_RegistrationRequest": {
            "type": "object",
            "required": [
                "id",
                "ts",
                "ver"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/validation.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.RegistrationRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "5.0.0"
                }
            }
        },
        "validation.ApiRequest_ResolveRequest": {
            "type": "object",
            "required": [
                "id",
                "ts",
                "ver"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/validation.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.ResolveRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "5.0.0"
                }
            }
        },
        "validation.ApiRequest_UpdateActorRequest": {
            "type": "object",
            "required": [
                "id",
                "ts",
                "ver"
            ],
            "properties": {
                "id": {
                    "type": "string",
                    "example": "api.actor.create"
                },
                "params": {
                    "$ref": "#/definitions/validation.RequestParams"
                },
                "request": {
                    "$ref": "#/definitions/validation.UpdateActorRequest"
                },
                "ts": {
                    "type": "string",
                    "example": "2023-01-01T00:00:00Z"
                },
                "ver": {
                    "type": "string",
                    "example": "5.0.0"
                }
            }
        },
        "validation.CredentialPayload": {
            "type": "object",
            "properties": {
                "documentId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "verifiableCredential": {
                    "$ref": "#/definitions/validation.VerifiableCredential"
                }
            }
        },
        "validation.DeleteCredentialRequest": {
            "type": "object",
            "properties": {
                "credentialId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "validation.ForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "actor@example.com"
                }
            }
        },
        "validation.GetCredentialRequest": {
            "type": "object",
            "properties": {
                "credentialId": {
                    "type": "string",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                }
            }
        },
        "validation.ListCredentialsRequest": {
            "type": "object"
        },
        "validation.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "alice@finternet"
                }
            }
        },
        "validation.RegistrationRequest": {
            "type": "object",
            "required": [
                "email",
                "entityType",
                "firstName",
                "lastName",
                "masterPublicKey",
                "password",
                "universalIdentifier"
            ],
            "properties": {
                "countryOfIncorporation": {
                    "description": "Business fields",
                    "type": "string",
                    "example": "US"
                },
                "countryOfResidence": {
                    "type": "string",
                    "example": "US"
                },
                "email": {
                    "type": "string",
                    "example": "actor@example.com"
                },
                "entityType": {
                    "type": "string",
                    "enum": [
                        "Individual",
                        "Business"
                    ],
                    "example": "Individual"
                },
                "firstName": {
                    "type": "string",
                    "example": "John"
                },
                "lastName": {
                    "type": "string",
                    "example": "Doe"
                },
                "masterPublicKey": {
                    "type": "string",
                    "example": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...\n-----END PUBLIC KEY-----"
                },
                "nationality": {
                    "description": "Individual fields",
                    "type": "string",
                    "example": "US"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "password123"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+1234567890"
                },
                "universalIdentifier": {
                    "type": "string",
                    "example": "actor123"
                }
            }
        },
        "validation.RequestParams": {
            "type": "object",
            "properties": {
                "msgid": {
                    "type": "string",
                    "example": "2f7c3a4e-8bcb-4b44-8cf6-84cc8f1d2a87"
                }
            }
        },
        "validation.ResolveRequest": {
            "type": "object",
            "required": [
                "universalIdentifier"
            ],
            "properties": {
                "universalIdentifier": {
                    "type": "string",
                    "example": "actor123"
                }
            }
        },
        "validation.UpdateActorRequest": {
            "type": "object",
            "properties": {
                "firstName": {
                    "type": "string",
                    "example": "Jane"
                },
                "lastName": {
                    "type": "string",
                    "example": "Smith"
                },
                "phoneNumber": {
                    "type": "string",
                    "example": "+0987654321"
                }
            }
        },
        "validation.VerifiableCredential": {
            "type": "object",
            "properties": {
                "@context": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "https://www.w3.org/2018/credentials/v1"
                    ]
                },
                "credentialSubject": {
                    "type": "object",
                    "additionalProperties": true
                },
                "id": {
                    "type": "string",
                    "example": "http://example.edu/credentials/3732"
                },
                "issuanceDate": {
                    "type": "string",
                    "example": "2025-10-23T06:25:25.191Z"
                },
                "issuer": {
                    "type": "string",
                    "example": "did:example:issuer"
                },
                "proof": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "VerifiableCredential"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Finternet UNITS APIs Documentation",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
