apiVersion: v1
kind: Pod
metadata:
    name: kafka-client
spec:
  # serviceAccount: ka
  containers:
  - name: kafka
    image: solsson/kafka:latest
    command:
    - sh
    - -c
    - "exec sleep infinity"